### ISSUE TITLE
Pitchfork layout link is 404

### ISSUE THREAD

**Issue by mzed** [ebu/ebu-adm-toolbox#3]
In readme.md, https://vector-of-bool.github.io/psl.html is 404.

**Comment by tomjnixon** [comment]
Thanks, i think this section needs reviewing/updating in general. Looks like the right link is now https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/spec/data/spec.bs
