### ISSUE TITLE
error at build time

### ISSUE THREAD

**Issue by Ragoon35** [ebu/ebu-adm-toolbox#5]
Hello,

I have an issue at build time with the target generate_config_schema_includes.

FAILED: data/schemas/CMakeFiles/generate_config_schema_includes
CreateProcess failed: The system cannot find the file specified.

I'm confused, in the Cmakefile comment it is written it should doesn't error despite the files not existing.

Thanks

**Comment by tomjnixon** [comment]
Hi, sorry about this, I didn't realise i was not following this repository yet...

I think I've fixed this, but if not, please re-open this issue.
