### ISSUE TITLE
README is confusing

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ebu-adm-toolbox#6]
There seem to lots of pieces from the git.ebu.io in there, which are misleading and confusing when not very familiar with compiling processes. Please review

**Comment by tomjnixon** [comment]
Ah, I thought I'd changed those -- I'll fix it.

Thanks for having a look.

**Comment by WernerBleisteiner** [comment]
Being lazy, I just c/p and ran into "no permission" (my EBU key had just expired). Got me into into checking all my ssh...and finally I realised it referring not to this repo😉

**Comment by tomjnixon** [comment]
laziness is a virtue :)
